name: Hello World
author: Crisz Mendoza
description: Some description
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: Crisz
outputs:
  time:
    description: The greeting time
runs:
  using: node12
  main: dist/index.js
